FROM gcc:latest as builder
MAINTAINER ehemdal@brandeis.edu
RUN mkdir /myapp
COPY ./code/hello.c /myapp
WORKDIR /myapp
RUN gcc -static -o myapp hello.c

FROM centos:latest
COPY --from=builder /myapp/myapp /myapp
ENTRYPOINT ./myapp
